### ISSUE TITLE
Create GitHub Actions to deploy the react app to github pages

### ISSUE THREAD

**Issue by KKghub** [HrithikKumar49/The-Guardian-Tech-News#4]
Currently the webapp works on local machine, It'd be nice to deploy the react app to github pages using github actions

**Comment by KKghub** [comment]
Some resources are:
https://medium.com/@mannyyang/how-to-deploy-a-react-app-to-github-pages-with-github-actions-efd430632a45
https://github.com/nchaulet/github-action-gh-pages

we need to create a yaml file I think to achieve this while the article talks about workflow file

**Comment by KKghub** [comment]
Created new branch `deploy-gh-pages` for this enhancement.
The deploy script has been added in package.json and working fine for deployment of react app on `gh-pages` branch. The only thing pending is automating the deployment using github actions.

**Comment by KKghub** [comment]
The automation was not possible using only `yarn deploy` command hence `peaceiris/actions-gh-pages@v3` action is being used to perform the automatic deployment

**Comment by KKghub** [comment]
The deployment is happening as expected. We can close this issue now

**Comment by HrithikKumar49** [comment]
Closing this issue
